volumes:
  gmfs-data-vol:
  gmfs-git-vol:
services:
  # Main Service
  gm-file-server:
    image: glidein-manager-file-server
    build: .
    environment:
      - REPO_URL=git@github.com:mwestphall/glidein-manager-test-upstream.git
      - SSH_KEY=/mnt/ssh/id_rsa
      - API_PREFIX=/api
    volumes:
      - ./volumes/ssh/:/mnt/ssh:ro
      - ./volumes/config/:/etc/gm-file-server/config:ro
      - gmfs-git-vol:/var/lib/git
      - gmfs-data-vol:/etc/gm-file-server/data
    ports:
      - "8080:80"
    healthcheck:
      test: "curl --fail http://localhost:80/api/public || exit 1"
      interval: 10s
      timeout: 5s 
      retries: 5
      start_period: 0s

  # Tests Container
  pytests:
    profiles: ["pytests"]
    build:
      context: .
      dockerfile: tests.Dockerfile
    env_file:
      - tests.env
    image: glidein-manager-tests
    depends_on:
      gm-file-server:
        condition: service_healthy
    environment:
      - API_PREFIX=/api
      - GM_ADDRESS=http://gm-file-server
      - CALLBACK_ADDRESS=http://pytests:8089/public/challenge/response
      - CLIENT_NAME=pytests
    working_dir: /srv/app
    volumes:
      - gmfs-data-vol:/etc/gm-file-server/data
    entrypoint: ['python3', '-m', 'pytest', '-s', 'test/${TEST_PKG}']
